export const images = {
  bgGameCardPlay: require('@/assets/images/bg-game-card-play.png'),
  bgGameColorPlay: require('@/assets/images/bg-game-color-play.png'),
  gameFlipCard: require('@/assets/images/game-flip-card.png'),
  gameFindColor: require('@/assets/images/game-find-color.png'),
  cao_thu: require('~/assets/images/achievement/cao_thu.png'),
  cham_chi: require('~/assets/images/achievement/cham_chi.png'),
  hoan_hao: require('~/assets/images/achievement/hoan_hao.png'),
  khong_the_can_pha: require('~/assets/images/achievement/khong_the_can_pha.png'),
  sieu_nhi: require('~/assets/images/achievement/sieu_nhi.png'),
  tan_binh: require('~/assets/images/achievement/tan_binh.png'),
  toc_do: require('~/assets/images/achievement/toc_do.png'),
  cards: require('@/assets/images/cards.png'),
  splash: require('@/assets/images/splash.png'),
  bgHome: require('@/assets/images/bg-home.png'),
  logoApp: require('@/assets/images/logo-app.png'),
  rope: require('@/assets/images/rope.png'),
  bgMode: require('@/assets/images/bg-mode.png'),
  bgFlipCard: require('@/assets/images/bg-game-flip-card.png'),
  bgColor: require('@/assets/images/bg-game-color.png'),
  bgBoard: require('@/assets/images/bg-board.png'),
  levelGame: require('@/assets/images/level-game.png'),
  bgAchievement: require('@/assets/images/bg-achievement.png'),
  boardTimeLine: require('@/assets/images/boardTimeLine.png'),
  cardActive: require('@/assets/images/icon-card-active.png'),
  cardDeActive: require('@/assets/images/iconCardDeActive.png'),
  iconStarActive: require('@/assets/images/star-level/icon-star-active.png'),
  iconStarDeActive: require('@/assets/images/star-level/icon-star-de-active.png'),
  bgModal: require('@/assets/images/bg-modal.png'),
  timeProcessBar: require('@/assets/images/time-duration.png'),
  starLeft: require('@/assets/images/star-result/star-left.png'),
  starRight: require('@/assets/images/star-result/star-right.png'),
  starCenter: require('@/assets/images/star-result/star-center.png'),
  starLeftActive: require('@/assets/images/star-result/star-left-active.png'),
  starRightActive: require('@/assets/images/star-result/star-right-active.png'),
  starCenterActive: require('@/assets/images/star-result/star-center-active.png'),
} as const //

export type ImageKeys = keyof typeof images // Tạo type dựa trên key của `images`

export default images
